### PR TITLE
Listen on [::] instead of 0.0.0.0, set IP family

### LINKED ISSUE #135: caused by Error: bind EINVAL 0.0.0.0
I'm getting "Error: bind EINVAL 0.0.0.0" in the server, and "WARNING: [youtube] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Error reaching POST /get_pot (caused by TransportError("HTTPConnectionPool(host=\'127.0.0.1\', port=4416): Read timed out. (read timeout=20.0)"))'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  ." in the client.  It looks like some simple user error, but I haven't figured it out yet.  I verified that I am able to reach jnn-pa.googleapis.com from my network using traceroute.

```
$ node build/main.js
Started POT server (v1.2.1) on port 4416
Failed to get descrambled challenge from Innertube, trying the /Create endpoint. (caused by Error: Innertube context unavailable)
Error: Error while attempting to retrieve BG challenge. (caused by Error: Error reaching POST https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create: All 3 retries failed. (caused by Error: bind EINVAL 0.0.0.0 (caused by Error: bind EINVAL 0.0.0.0)))
    at SessionManager.getDescrambledChallenge (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:227:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionManager.generateTokenMinter (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:233:38)
    at async SessionManager.generatePoToken (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:391:29)
    at async file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/main.js:34:29
```

Tried again:
```
Started POT server (v1.2.1) on port 4416
Using challenge from the webpage
Failed to get descrambled challenge from Innertube, trying the /Create endpoint. (caused by Error: Error reaching GET https://www.google.com/js/th/V7ja38rKAn2jOTQkNfar3YpNMzeElth0DSbilEGGIuc.js: All 3 retries failed. (caused by Error: bind EINVAL 0.0.0.0 (caused by Error: bind EINVAL 0.0.0.0)))
Error: Error while attempting to retrieve BG challenge. (caused by Error: Error reaching POST https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create: All 3 retries failed. (caused by Error: bind EINVAL 0.0.0.0 (caused by Error: bind EINVAL 0.0.0.0)))
    at SessionManager.getDescrambledChallenge (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:227:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionManager.generateTokenMinter (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:233:38)
    at async SessionManager.generatePoToken (file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/session_manager.js:391:29)
    at async file:///home/self/src/yt-dlp/bgutil-ytdlp-pot-provider/20250808/bgutil-ytdlp-pot-provider/server/build/main.js:34:29
```

yt-dlp output:
```
[debug] Command-line config: ['-4', '-v', '--live-from-start', '--socket-timeout', '5', '--embed-metadata', '--embed-info-json', '--keep-fragments', '-k', '--write-info-json', '-f', '137+140', 'https://youtu.be/mhJRzQsLZGg']
[debug] User config "/home/self/yt-dlp.conf": ['--ffmpeg-location', '/home/self/src/yt-dlp/6498/yt-dlp/ffmpeg-binary-get/ffmpeg-master-latest-linux64-gpl/bin']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.07.21 from yt-dlp/yt-dlp [9951fdd0d] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-1018-lowlatency-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-112327-g9078dc0c52-20231005 (setts), ffprobe N-112327-g9078dc0c52-20231005, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.08.03, mutagen-1.47.0, requests-2.32.4, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.5.0, websockets-15.0.1, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: /home/self/.yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins, /home/self/.local/lib/python3.10/site-packages/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/self/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot:bgutil:script] Script path doesn't exist: /home/self/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.2.1 (external), bgutil:script-1.2.1 (external, unavailable)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://youtu.be/mhJRzQsLZGg
[youtube] mhJRzQsLZGg: Downloading webpage
[youtube] mhJRzQsLZGg: Downloading tv client config
[debug] Loading youtube-sts.761c1f12-main from cache
[youtube] mhJRzQsLZGg: Downloading tv player API JSON
[debug] [youtube] mhJRzQsLZGg: tv player response playability status: ERROR
[youtube] mhJRzQsLZGg: Downloading ios player API JSON
[debug] [youtube] [pot:bgutil:http] No base_url provided, defaulting to http://127.0.0.1:4416
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
WARNING: [youtube] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Error reaching POST /get_pot (caused by TransportError("HTTPConnectionPool(host=\'127.0.0.1\', port=4416): Read timed out. (read timeout=20.0)"))'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  .
[debug] [youtube] mhJRzQsLZGg: web client dash formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=web.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
ERROR: [youtube] mhJRzQsLZGg: The following content is not available on this app.
  File "/tmp/yt-dlp.2289803.17634/yt_dlp/extractor/common.py", line 761, in extract
    ie_result = self._real_extract(url)
  File "/tmp/yt-dlp.2289803.17634/yt_dlp/extractor/youtube/_video.py", line 3945, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/tmp/yt-dlp.2289803.17634/yt_dlp/extractor/common.py", line 1273, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

### PR DESCRIPTION
**Pull request by Brainicism**
`::` is ipv6 notation to support routing traffic from all addresses. On dual-stack machines, this works for both ipv6/ipv4 as well. In the rare case that the user's machine doesn't support this, we fallback to 0.0.0.0. 

Also set the IP family.

Should fix #135 and maybe #118, as we are now listening on both ipv6 and ipv4 interfaces.

### CODE REVIEW

File: server/src/session_manager.ts [hunk 1]
```diff
@@ -106,6 +106,11 @@ class ProxySpec {
             return new ProxyAgent({
                 getProxyForUrl: () => pxyStr,
                 localAddress: sourceAddress,
+                family: sourceAddress
+                    ? sourceAddress.includes(":")
```
Comment (grqz) [inline server/src/session_manager.ts]: is there a better way of detecting IPv6 addresses? Do they always have a colon in them?

Comment (Brainicism) [reply server/src/session_manager.ts]: This is how yt-dlp does it as well
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp%2Fnetworking%2F_helper.py#L246

Comment (grqz) [reply server/src/session_manager.ts]: Lets add it to line 92 as well
```ts
        const { proxyUrl, sourceAddress, disableTlsVerification } = this;
        const family = sourceAddress
            ? sourceAddress.includes(":")
                ? 6
                : 4
            : undefined;

        if (!proxyUrl) {
            return new Agent({
                family,
                localAddress: sourceAddress,
                rejectUnauthorized: !disableTlsVerification,
            });
        }
```
btw do you think it's more readable to put 6 and 4 on the same line?

File: server/src/session_manager.ts [hunk 2]
```diff
@@ -55,9 +55,15 @@ class ProxySpec {
     public proxyUrl?: URL;
     public sourceAddress?: string;
     public disableTlsVerification: boolean = false;
+    public ipFamily: number | undefined = 0;
```
Comment (grqz) [inline server/src/session_manager.ts]:
```suggestion
    public readonly ipFamily?: number;
```
should we do this

**Review by grqz — CHANGES_REQUESTED** [review]

**Review by grqz — APPROVED** [review]
LGTM
